services:
  backend:
    build: ./back
    container_name: apiPatriMaster
    ports:
      - "3001:3001"
    env_file:
      - ./back/.env
    restart: always

  frontend:
    build: ./front
    container_name: PatriMaster
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
