# services:
#   backend:
#     build: ./back
#     container_name: apiPatriMaster
#     ports:
#       - "3001:3001"
#     env_file:
#       - ./back/.env
#     restart: always

#   frontend:
#     build: ./front
#     container_name: PatriMaster
#     ports:
#       - "80:80"
#     depends_on:
#       - backend
#     restart: always

# version: '3.9'

# services:
#   backend:
#     build: ./back
#     container_name: apiPatriMaster
#     ports:
#       - "3001:3001" 
#     environment:
#       - HOST=0.0.0.0
#     env_file:
#       - ./back/.env
#     restart: always

#   frontend:
#     build: ./front
#     container_name: PatriMaster
#     environment:
#       - HOST=0.0.0.0
#     restart: always

#   nginx:
#     image: nginx:latest
#     container_name: nginxPatrimonio
#     ports:
#       - "80:80"
#     environment:
#       - HOST=0.0.0.0
#     volumes:
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
#     depends_on:
#       - frontend
#       - backend
#     restart: always

version: '3.9'

services:
  backend:
    build: ./back
    container_name: apiPatriMaster
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    build: ./front
    container_name: PatriMaster
    ports:
      - "80:80"   # container ouve porta 80, host usa 8080
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "81:81"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./dist:/usr/share/nginx/html
