version: '3.9'

services:
  backend:
    build: ./back
    container_name: apiPatriMaster
    ports:
      - "3001:3001"
    restart: always

  frontend:
    build: ./front
    container_name: PatriMaster
    ports:
      - "80:80"   # FRONT → porta 80 do HOST e porta 80 do CONTAINER
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginxPatrimonio
    ports:
      - "81:81"   # HOST 81 → CONTAINER 80 (NGINX)
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    restart: always
